[book]
authors = ["Richard Crosby", "Pelle Braendgaard"]
language = "en"
multilingual = false
src = "src"
title = "Transaction Authorization Protocol (TAP)"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.frontmatter]
command = "mdbook-frontmatter"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

